
-- Insert 20 Multiple Choice questions
INSERT INTO MultipleQuestion (id, qestion, correct_answer) VALUES
(41, 'What house is Harry Potter sorted into?', 'A'),
(42, 'What color is Yodas lightsaber?', 'B'),
(43, 'What instrument does Squidward play?', 'C'),
(44, 'What is Bugs Bunnys catchphrase?', 'A'),
(45, 'What is Luffys dream?', 'A'),
(46, 'Who is Woodys best friend in Toy Story?', 'B'),
(47, 'What is the name of the potion master at Hogwarts?', 'C'),
(48, 'What planet is Luke Skywalker from?', 'D'),
(49, 'What is SpongeBobs favorite activity?', 'A'),
(50, 'What is Daffy Ducks signature phrase?', 'B'),
(51, 'What is Zoros goal in One Piece?', 'C'),
(52, 'What is Buzz Lightyears catchphrase?', 'D'),
(53, 'What is the name of Gryffindors ghost?', 'A'),
(54, 'What is the name of Han Solos ship?', 'B'),
(55, 'What is the name of SpongeBobs snail?', 'C'),
(56, 'Who is the main antagonist in the Looney Tunes show?', 'D'),
(57, 'What is the name of Luffys brother?', 'A'),
(58, 'What is the name of the space ranger in Toy Story?', 'B'),
(59, 'What is Hermiones last name?', 'C'),
(60, 'What is the name of the robot in Star Wars?', 'A');

-- Insert choices for Multiple Choice questions
INSERT INTO MultipleChoice (qestion_id, choice, choice_text) VALUES
(41, 'A', 'Gryffindor'),
(41, 'B', 'Hufflepuff'),
(41, 'C', 'Ravenclaw'),
(41, 'D', 'Slytherin'),
(42, 'A', 'Red'),
(42, 'B', 'Green'),
(42, 'C', 'Blue'),
(42, 'D', 'Purple'),
(43, 'A', 'Guitar'),
(43, 'B', 'Trumpet'),
(43, 'C', 'Clarinet'),
(43, 'D', 'Piano'),
(44, 'A', 'Whats up, Doc?'),
(44, 'B', 'Thats all folks!'),
(44, 'C', 'Eh, whats cookin?'),
(44, 'D', 'Whats going on?'),
(45, 'A', 'To become the Pirate King'),
(45, 'B', 'To find the One Piece'),
(45, 'C', 'To become a swordsman'),
(45, 'D', 'To explore the world'),
(46, 'A', 'Buzz Lightyear'),
(46, 'B', 'Slinky Dog'),
(46, 'C', 'Mr. Potato Head'),
(46, 'D', 'Rex'),
(47, 'A', 'Minerva McGonagall'),
(47, 'B', 'Albus Dumbledore'),
(47, 'C', 'Severus Snape'),
(47, 'D', 'Remus Lupin'),
(48, 'A', 'Naboo'),
(48, 'B', 'Endor'),
(48, 'C', 'Coruscant'),
(48, 'D', 'Tatooine'),
(49, 'A', 'Jellyfishing'),
(49, 'B', 'Cooking'),
(49, 'C', 'Cleaning'),
(49, 'D', 'Sleeping'),
(50, 'A', 'Youre despicable!'),
(50, 'B', 'Youre dethpicable!'),
(50, 'C', 'Thats all folks!'),
(50, 'D', 'Whats up, Doc?'),
(51, 'A', 'To become the Pirate King'),
(51, 'B', 'To find the One Piece'),
(51, 'C', 'To become the worlds greatest swordsman'),
(51, 'D', 'To explore the world'),
(52, 'A', 'Prepare for trouble!'),
(52, 'B', 'Reach for the sky!'),
(52, 'C', 'I am Buzz Lightyear!'),
(52, 'D', 'To infinity, and beyond!'),
(53, 'A', 'Nearly Headless Nick'),
(53, 'B', 'Moaning Myrtle'),
(53, 'C', 'The Grey Lady'),
(53, 'D', 'The Bloody Baron'),
(54, 'A', 'X-wing'),
(54, 'B', 'Millennium Falcon'),
(54, 'C', 'TIE Fighter'),
(54, 'D', 'Star Destroyer'),
(55, 'A', 'Rex'),
(55, 'B', 'Sheldon'),
(55, 'C', 'Gary'),
(55, 'D', 'Larry'),
(56, 'A', 'Elmer Fudd'),
(56, 'B', 'Yosemite Sam'),
(56, 'C', 'Sylvester the Cat'),
(56, 'D', 'Marvin the Martian'),
(57, 'A', 'Ace'),
(57, 'B', 'Zoro'),
(57, 'C', 'Shanks'),
(57, 'D', 'Sanji'),
(58, 'A', 'Woody'),
(58, 'B', 'Buzz Lightyear'),
(58, 'C', 'Rex'),
(58, 'D', 'Mr. Potato Head'),
(59, 'A', 'Jean'),
(59, 'B', 'Jane'),
(59, 'C', 'Granger'),
(59, 'D', 'Lily'),
(60, 'A', 'R2-D2'),
(60, 'B', 'C-3PO'),
(60, 'C', 'BB-8'),
(60, 'D', 'K-2SO');
